### PR TITLE
Fix jest-native peer dependency on react-native and migrate @testing-library/react-native support to v7+

### LINKED ISSUE #29: Consider spliting @moxy/jest-config-testing-library into a web and native variant
Reason being that `@moxy/jest-config-testing-library` installs `@testing-library/jest-native` which as a peerDependency of `react-native`, which is weird on web projects.

```
npm WARN @testing-library/jest-native@3.3.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN @testing-library/jest-native@3.3.0 requires a peer of react-test-renderer@* but none is installed. You must install peer dependencies yourself.
```

### LINKED ISSUE #30: Migrate to React Native Testing Library by Callstack
Native Testing library deprecation notice: https://github.com/testing-library/native-testing-library/blob/master/README.md#%EF%B8%8F-deprecation-notice-%EF%B8%8F.

Migration guide available at https://callstack.github.io/react-native-testing-library/docs/migration-v7/.

### PR DESCRIPTION
**Pull request by acostalima**
v7+ migration guide: https://callstack.github.io/react-native-testing-library/docs/migration-v7/

Notable changes:
- `@testing-library/react-native` now uses React Native's Jest preset instead of providing its own preset on top of React Native's.
- It is no longer necessary to add `@testing-library/react-native/cleanup-after-each` to Jest's environment setup hook. The behavior is now consistent with React Testing Library (RTL).

Fixes #29 
Resolves #30

### CODE REVIEW

**Comment by satazor** [comment]
Looks good, you can merge

**Review by ruipneves — APPROVED** [review]

File: jest/resolve-modules.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 'use strict';
 
 const VIRTUAL_MODULES = [
-    '@testing-library/react-native/cleanup-after-each',
+    // Add here modules that are not installed and for which you'd like, e.g., mock require.resolve
```
Comment (threequartersjohn) [inline jest/resolve-modules.js:4]: As discussed, can you please change this message to something more clear?

```suggestion
    // Add here modules that are not installed but which you still need to require by using require.resolve
```
